version: '3.8'

services:
  steam-api:
    image: lilchim/steam-api-dotnet:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SteamApi__ApiKey=${STEAM_API_KEY}
      - ApiKey__RequireApiKey=false
    networks:
      - sgnome-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sgnome-network
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - sgnome-network
    volumes:
      - redis-insight:/data   

  sgnome-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - SteamApi__BaseUrl=http://steam-api:8080
      - SteamApi__ApiKey=${STEAM_API_KEY:-dev-key}
    depends_on:
      - steam-api
      - redis
    networks:
      - sgnome-network

volumes:
  redis-data:

networks:
  sgnome-network:
    driver: bridge 